### ISSUE TITLE
ERROR: Cert does not exist!

### ISSUE THREAD

**Issue by adamradocz** [linuxserver/docker-letsencrypt#107]
When I run the image at the first time, I got the following error message. The 80 and the 443 ports are forwarded.
```
DH parameters successfully created - 2048 bits
SUBDOMAINS entered, processing
Only subdomains, no URL in cert
Sub-domains processed are:  -d xxx.duckdns.org
E-mail address entered: xxx@gmail.com
Generating new certificate
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
Performing the following challenges:
Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA.
Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA.
IMPORTANT NOTES:
 - Your account credentials have been saved in your Certbot
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Certbot so
   making regular backups of this folder is ideal.
ERROR: Cert does not exist! Please see the validation error above. The issue may be due to incorrect dns or port forwarding settings. Please fix your settings and recreate the container
```

Host OS: Ubuntu Server 17.10.1
Docker version:
```
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:11:14 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:09:47 2017
  OS/Arch:      linux/amd64
  Experimental: false
```
Docker compose version:
```
docker-compose version 1.8.0, build unknown
docker-py version: 1.9.0
CPython version: 2.7.14
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```

The command I run: `sudo docker-compose up -d`
The `docker-compose.yml` file's content:
```
version: '2'
services:

  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
      - 443:443
    volumes:
      - /opt/appdata/letsencrypt:/config
    environment:
      - EMAIL=xxx@gmail.com
      - URL=duckdns.org
      - SUBDOMAINS=xxx
      - ONLY_SUBDOMAINS=true
      - DHLEVEL=2048
      - TZ=Europe/Budapest
      - PUID=1000
      - PGID=1000
```
