### ISSUE TITLE
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address in use)

### ISSUE THREAD

**Issue by adamradocz** [linuxserver/docker-letsencrypt#157]
I get the following error message:
```
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address in use)
```

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Host OS: `Ubuntu 18.04.01`

Run command:
```
version: '3'
services:

  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    depends_on:
      - duckdns
    restart: always
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - /opt/appdata/letsencrypt:/config
    environment:
      - EMAIL=xxx@gmail.com
      - URL=xxx.duckdns.org
      - SUBDOMAINS=plex,deluge
      - ONLY_SUBDOMAINS=true
      - VALIDATION=http
      - DHLEVEL=2048
      - TZ=Europe/Budapest
      - PUID=1000
      - PGID=1000
```

Docker log output:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing...
Variables set:
PUID=1000
PGID=1000
TZ=Europe/Budapest
URL=xxx.duckdns.org
SUBDOMAINS=plex,deluge
EXTRA_DOMAINS=
ONLY_SUBDOMAINS=true
DHLEVEL=2048
VALIDATION=http
DNSPLUGIN=
EMAIL=xxx@gmail.com
STAGING=

2048 bit DH parameters present
SUBDOMAINS entered, processing
SUBDOMAINS entered, processing
Only subdomains, no URL in cert
Sub-domains processed are:  -d plex.xxx.duckdns.org -d deluge.xxx.duckdns.org
E-mail address entered: xxx@gmail.com
http validation is selected
Certificate exists; parameters unchanged; attempting renewal
<------------------------------------------------->

<------------------------------------------------->
cronjob running on Wed Aug 22 08:02:19 CEST 2018
Running certbot renew
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/plex.xxx.duckdns.org.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Cert not yet due for renewal

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

The following certs are not due for renewal yet:
  /etc/letsencrypt/live/plex.xxx.duckdns.org/fullchain.pem expires on 2018-11-06 (skipped)
No renewals were attempted.
No hooks were run.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[cont-init.d] 50-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address in use)
Server ready
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address in use)
nginx: [emerg] still could not bind()
```
