### ISSUE TITLE
Failed to set a seccomp profile on a worker thread Continuously In Logs

### ISSUE THREAD

**Issue by Barrow1990** [linuxserver/docker-letsencrypt#190]
My Docker-Compose File:
```
version: '3'

services:
  ReverseProxy:
    image: linuxserver/letsencrypt
    network_mode: 'Lab'
    cap_add:
      - NET_ADMIN
    environment:
      - PGID=1028
      - PUID=100
      - EMAIL=
      - URL=
      - VALIDATION=HTTP
      - STAGING=true
      - TZ=Europe/London
    volumes:
      - /config:/config
    ports:
      - 4480:80
      - 4443:443
    container_name: Lab_ReverseProxy
    hostname: ReverseProxy
```

My Logs Are (docker logs -f Lab_ReverseProxy):

> Failed to set a seccomp profile on a worker thread
> Failed to set a seccomp profile on a worker thread
> Failed to set a seccomp profile on a worker thread
> Failed to set a seccomp profile on a worker thread
> Failed to set a seccomp profile on a worker thread
> Failed to set a seccomp profile on a worker thread
> Failed to set a seccomp profile on a worker thread
> Failed to set a seccomp profile on a worker thread
> Failed to set a seccomp profile on a worker thread

It adds another 1 every second or so. Ive googled it and cant seem to find anything related
It sets up the certs fine and this is after it all

**Comment by nemchik** [comment]
Just a few questions about your compose (that might be unrelated)

- network mode: shouldn't this be bridge, host, or `container:OtherContainerName` (there's other options as well, but I don't think `'Lab'` is valid)
- URL: this is filled out in your file and blank here just so you're not sharing your personal info right?
- VALIDATION: I'm not sure it matters, but I use `http` (lowercase)

**Comment by Barrow1990** [comment]
- Network mode: I have a bridged network named Lab
- URL: Yes you are correct
- Validation: I have no issues with the certificate being created.

**Comment by j0nnymoe** [comment]
You're network mode is set incorrectly: https://docs.docker.com/compose/compose-file/#network_mode
If you have a custom network, use: https://docs.docker.com/compose/compose-file/#networks

**Comment by Barrow1990** [comment]
So on your links i have changed the network so now my new docker-compose file is as follows:
```
version: '3'

services:
  ReverseProxy:
    image: linuxserver/letsencrypt
    networks:
      - ReverseProxy
    cap_add:
      - NET_ADMIN
    environment:
      - PGID=1028
      - PUID=100
      - EMAIL=email@domain.co.uk
      - URL=tld.domain.co.uk
      - VALIDATION=HTTP
      - STAGING=true
      - TZ=Europe/London
    volumes:
      - /config:/config
    ports:
      - 4480:80
      - 4443:443
    container_name: Lab_ReverseProxy
    hostname: ReverseProxy

networks:
  ReverseProxy:
```

And im still getting the above in the logs.

**Comment by nemchik** [comment]
Happy monday. Now that I've had some coffee I think you can't use port `4480:80` with `http` validation. You should use port `80:80` or switch to `dns` validation.

**Comment by tobbenb** [comment]
As long as he port forward 80 to 4480 in his router it should work.

**Comment by tobbenb** [comment]
If you Google the error, it looks like it's related to docker compose and some security policy not set correctly. Does the same error happen if you add SYS_ADM In?

**Comment by Barrow1990** [comment]
Ive just tried it using the following with docker create / start:

```
docker create \
  --cap-add=NET_ADMIN \
  --name=Lab_ReverseProxy \
  -v /config:/config \
  -e PGID=100 \
  -e PUID=1028  \
  -e EMAIL=email@domain.co.uk \ 
  -e URL=sub.domain.co.uk \
  -e VALIDATION=HTTP \
  -e TZ=Europe/London \
  -p 80:80 \
  -p 443:443 \
  linuxserver/letsencrypt
```

**Comment by tobbenb** [comment]
Which OS are you using and which version of docker (Source is docker or OS package?)?

**Comment by Barrow1990** [comment]
Docker pckage on Synology. 
I will test on a Debian Install tomorrow

**Comment by tobbenb** [comment]
I'm almost certain it's a Synology issue then...

**Comment by Barrow1990** [comment]
Thanks for all your reply's. Ive just tried it on a Docker on Debian and it seems to have worked as expected. No errors what so ever. So its defiantly something related to how the package is made.

**Comment by tobbenb** [comment]
Is the docker package old? You could try to contact synology and see what they say.

**Comment by Barrow1990** [comment]
Yea i have just checked versions and its an older version:

Synology Docker: 
```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.8
 Git commit:   9f07f0e-synology
 Built:        Fri May 11 13:41:13 2018
 OS/Arch:      linux/amd64
Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.8
 Git commit:   9f07f0e-synology
 Built:        Fri May 11 13:41:13 2018
 OS/Arch:      linux/amd64
 Experimental: false
```
Debian Docker:
```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:09:33 2018
 OS/Arch:           linux/amd64
 Experimental:      false
Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:07:38 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by ohadbenita** [comment]
Is there any way to upgrade the Synology docker package ? I'm having the exact same issue

**Comment by j0nnymoe** [comment]
Contact Synology 😄

**Comment by ohadbenita** [comment]
Just did, I'll update their response here

**Comment by j0nnymoe** [comment]
👌

**Comment by jodumont** [comment]
based on few research; it's, as mentioned earlier, based on the client side
as suggest as a temporary solution [here](https://github.com/docker/compose/issues/2813);

as a temporary solution you could run your image/composer without seccomp
`seccomp:unconfined`

hopefully for you; synology will probably fix this in a near future release.

**Comment by j33p4meplz** [comment]
I tried that work around and it did not help on my syno, fyi.

**Comment by rfgamaral** [comment]
> hopefully for you; synology will probably fix this in a near future release.

As far as I'm aware (after contacting Synology about a different Docker issue) Synology is only responsible for publishing the Docker package to the repository, Docker are the ones responsible for development of the package (even if it's a Synology package). Which is weird, why would they use an older version?

Does anyone have any idea how to contact Docker themselves about updating they're Synology package to include the latest Docker version?

**Comment by rfgamaral** [comment]
Now more on topic, how bad is it to keep this Docker container running with this message being logged every second indefinitely?

**Comment by rfgamaral** [comment]
Another question for the guys using this in a Synology... My idea was to used the generated certificate in the Synology itself but the certificate can only be manually imported which I'm not willing to do every time the certificate expires (if only the Synology Let's Encrypt implementation supported `dns` validation). How are you guys doing it?

**Comment by aptalca** [comment]
I highly doubt that docker the company packages the docker service for synology specifically, but I could be wrong.

We use certbot, the official letsencrypt acme client to retrieve certs.

**Comment by j0nnymoe** [comment]
Synology would compile it themselves like QNAP do.

**Comment by rfgamaral** [comment]
Sure, but Docker the company are the ones that are probably coding and distributing the package code. Synology might compile and package it for Synology devices, but they are not the ones developing it.

**Comment by aptalca** [comment]
The issue is likely due to how it is compiled for synology, as the docker system does not exhibit that issue on any other systems we tested.

Libseccomp is a dependency for docker (for runc specifically). My guess is that synology screwed up something with the compile flags related to libseccomp or the environment.

**Comment by michelde** [comment]
I'm also having the same problem on my Synology running Docker. Let's hope next Docker version will bring a fix.

**Comment by j33p4meplz** [comment]
While still getting the error, the LE container is doing its job on my Syno
box. it seems to be more of an alert than an error.

**Comment by charliwest** [comment]
I get this on the PI version btw, found this after googling the error. I am using the linuxserver arm version.

**Comment by jamorin** [comment]
After I got the container working on my Synology NAS, I used logging driver "none" to suppress the warning.

Caveat is that I don't get any logs from the container. But feel like this maybe stops unnecessary disk IO from storing this log message every second!

```yaml
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    restart: unless-stopped
    logging:
      driver: "none"
    cap_add:
    - NET_ADMIN
    environment:
    <OMMITTED>
    volumes:
    - /volume1/docker/letsencrypt:/config
```
