### ISSUE TITLE
Reverse proxy not working /w subdomains and docker compose.

### ISSUE THREAD

**Issue by Dulanic** [linuxserver/docker-letsencrypt#233]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

For some reason when running this container with docker-compose, it does not route subdomain traffic as it should. It works fine if I do a docker run.

Ubuntu 18.04

Working /w docker run:
```
docker create \
  --cap-add=NET_ADMIN \
  --network=opt_default \
  --name=letsencrypt \
  -v /docker/containers/letsencrypt/config:/config \
  -e PGID=1000 -e PUID=1000  \
  -e EMAIL=email \
  -e URL=domain \
  -e SUBDOMAINS=,www,nzbget,radarr,sonarr,transmission \
  -e VALIDATION=http \
  -p 80:80 -p 443:443 \
  -e TZ=America/Chicago \
  linuxserver/letsencrypt
```

Not working /w compose, it is routing to main website instead.

 ```
 letsencrypt:
    image: linuxserver/letsencrypt:latest
    container_name: letsencrypt
    volumes:
      - /docker/containers/letsencrypt/config:/config
    ports:
      - 443:443
      - 80:80
    cap_add:
      - NET_ADMIN
    environment:
      - PGID=1000
      - PUID=1000
      - EMAIL=email
      - URL=domain
      - SUBDOMAINS=,www,nzbget,radarr,sonarr,transmission
      - VALIDATION=http
      - TZ=America/Chicago
      - ONLY_SUBDOMAINS=false
    restart: unless-stopped

```

![image](https://user-images.githubusercontent.com/2948206/48592060-44ec0d00-e90c-11e8-87c8-0830ae3ca621.png)

curl from within the container showing, it would pull radarr if it was routing the proxy correctly.
```

dulanic@mediaserver:~$ sudo docker exec -it letsencrypt /bin/bash                                                                                                                            root@da5d84a93a0b:/$ ping radarr
PING radarr (172.21.0.8): 56 data bytes
64 bytes from 172.21.0.8: seq=0 ttl=64 time=0.109 ms
64 bytes from 172.21.0.8: seq=1 ttl=64 time=0.089 ms
^C
--- radarr ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.089/0.099/0.109 ms
root@da5d84a93a0b:/$ curl radarr:7878
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Radarr</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">

    <!-- Windows Phone -->
    <meta name="msapplication-navbutton-color" content="#272727">

```
 

Both looked identical no errors

No

it seems that all subdomain traffic is routing to the main html page for unknown reason when using docker-compose.
