### ISSUE TITLE
Uploading large (>2 MB) file fails

### ISSUE THREAD

**Issue by azinchen** [linuxserver/docker-letsencrypt#255]
docker-compose.yml example

```
version: '3'

services:
  nextcloud:
    image: linuxserver/nextcloud:latest
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/nextcloud-data:/data
      - ./volumes/nextcloud-config:/config

  letsencrypt:
    image: linuxserver/letsencrypt:latest
    restart: always
    ports:
      - 8888:443/tcp
    cap_add:
      - net_admin
    environment:
      - EMAIL=***
      - URL=***
      - SUBDOMAINS=***
      - ONLY_SUBDOMAINS=true
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - STAGING=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/letsencrypt:/config
    depends_on:
      - nextcloud
```

As template of proxy file I used nextcloud.subdomain.conf.sample

When I tried to upload big files I got error in ./volumes/letsencrypt/log/nginx/access.log file
```
192.168.1.1 - admin [11/Jan/2019:01:35:08 +0300] "PROPFIND /remote.php/dav/files/admin/Videos/Touch%20Screen%20issue.mp4 HTTP/1.1" 404 5 "-" "NetBox/2.3.0 neon/0.30.1"
192.168.1.1 - admin [11/Jan/2019:01:35:12 +0300] "PUT /remote.php/dav/files/admin/Videos/Touch%20Screen%20issue.mp4 HTTP/1.1" 413 199 "-" "NetBox/2.3.0 neon/0.30.1"
192.168.1.1 - admin [11/Jan/2019:01:35:13 +0300] "PROPFIND /remote.php/dav/files/admin/Videos HTTP/1.1" 207 596 "-" "NetBox/2.3.0 neon/0.30.1"
```
