### ISSUE TITLE
root domain certs not updated.

### ISSUE THREAD

**Issue by aegie** [linuxserver/docker-letsencrypt#256]
I'm running my proxied containers on a Synology nas. I managed to get everything up and running, received new certs for my subdomains, but my root domains has the same certificate. It was not removed and updated.

Prior to using the letsencrypt container, I got my certs using this method: https://github.com/Neilpang/acme.sh/wiki/Synology-NAS-Guide and getting the certs using acme.sh

How can I revoke the other certs, so that letsencrypt can take care of my root domain as well? 

And a second question, not related to the topic, still: could I proxy my synology interface from `domain.net:5066` to `ds.domain.net`?

By the way, here is my config. Pretty stocked about it, thanks linuxserver, awesome job!

```
version: '3'

services:
  ReverseProxy:
    image: linuxserver/letsencrypt
    restart: unless-stopped
    logging:
      driver: "none"
    ports:
      - "4480:80"
      - "4443:443"
    volumes:
      - /volume1/mediatools/letsencrypt:/config
    cap_add:
      - NET_ADMIN      
    networks:
      - media
    container_name: ReverseProxy
    environment:
      - PUID=1027
      - PGID=100
      - EMAIL=my@email.net
      - URL=mydomain.net
      - SUBDOMAINS=www,ds,heimdall,sonarr,radarr,lidarr,znc,ombi,rutorrent
      - TZ=Europe/Paris
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare 

  sonarr:
    depends_on:
      - ReverseProxy
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    volumes:
      - /volume1/Media/TV:/tv
      - /volume1/Media:/downloads
      - /volume1/mediatools/sonarr:/config
    environment:
      - TZ=Europe/Paris
      - PUID=1027
      - PGID=100
    networks:
      - media
    container_name: sonarr

  radarr:
    depends_on:
      - ReverseProxy
    image: linuxserver/radarr:latest
    restart: unless-stopped
    volumes:
      - /volume1/Media/Movies:/movies
      - /volume1/Media:/downloads
      - /volume1/mediatools/radarr:/config
    environment:
      - TZ=Europe/Paris
      - PUID=1027
      - PGID=100
    networks:
      - media
    container_name: radarr
            
  lidarr:
    depends_on:
      - ReverseProxy
    image: linuxserver/lidarr:latest
    restart: unless-stopped
    volumes:
      - /volume1/Media/Music:/music
      - /volume1/Media:/downloads
      - /volume1/mediatools/lidarr:/config
    environment:
      - TZ=Europe/Paris
      - PUID=1027
      - PGID=100            
    networks:
      - media
    container_name: lidarr      
            
  heimdall:
    depends_on:
      - ReverseProxy
    image: linuxserver/heimdall:latest
    restart: unless-stopped
    volumes:
      - /volume1/mediatools/heimdall:/config
    environment:
      - TZ=Europe/Paris
      - PUID=1027
      - PGID=100            
    networks:
      - media
    container_name: heimdall      
            
  ombi:
    depends_on:
      - ReverseProxy
    image: linuxserver/ombi:latest
    restart: unless-stopped
    volumes:
      - /volume1/mediatools/ombi:/config
    environment:
      - TZ=Europe/Paris
      - PUID=1027
      - PGID=100     
    networks:
      - media
    container_name: ombi      
            
  znc:
    depends_on:
      - ReverseProxy
    image: linuxserver/znc:latest
    restart: unless-stopped
    volumes:
      - /volume1/mediatools/znc:/config
    environment:
      - TZ=Europe/Paris
      - PUID=1027
      - PGID=100
    networks:
      - media
    container_name: znc 
    
  rutorrent:
    depends_on:
      - ReverseProxy
    image: linuxserver/rutorrent:latest
    restart: unless-stopped
    ports:
      - 51413:51413
    volumes:
      - /volume1/Media:/downloads
      - /volume1/mediatools/rutorrent:/config
    environment:
      - TZ=Europe/Paris
      - PUID=1027
      - PGID=100
    networks:
      - media
    container_name: rutorrent      

networks:
      media:
```
