### ISSUE TITLE
LDAP login loop when changing Heimdall users

### ISSUE THREAD

**Issue by happysamm** [linuxserver/docker-letsencrypt#297]
This is probably a config error on my part, but I'm having trouble finding it.

I request my heimdall subdomain, and am challenged for LDAP credentials, which I enter, and they are accepted.

When I try to change users in Heimdall though, the /login page which challenges me is not Heimdall's login page, but the LDAP login page. Entering credentials in this page just reloads the LDAP login page.

So I'm wondering how to go about using ldap-auth with reverse-proxied heimdall, since the /login page seems to conflict on these two.

Thanks in advance!

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	
CentOS-7 host machine

### docker-compose.yml:
```
version: "2"

services:

  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - SUBDOMAINS=${DUCKDNS_SUBDOMAIN}
      - TOKEN=${DUCKDNS_TOKEN}
      - LOG_FILE=true
    volumes:
      - ${DOCKER_CONFIGS}/duckdns/config:/config
    restart: unless-stopped

  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    depends_on:
      - duckdns
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - URL=${DUCKDNS_SUBDOMAIN}.duckdns.org
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNS_TOKEN}
      - EMAIL=${DUCKDNS_EMAIL}
      - DHLEVEL=4096
    volumes:
      - ${DOCKER_CONFIGS}/letsencrypt/config:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
	
  ldap-auth:
    image: linuxserver/ldap-auth
    container_name: ldap-auth
    depends_on:
      - openldap
    environment:
       - TZ=${TIMEZONE}
    ports:
      - 8888:8888
      - 9000:9000
    restart: unless-stopped

  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    depends_on:
      - letsencrypt
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${DOCKER_CONFIGS}/heimdall/config:/config
    ports:
      - 8443:443
    restart: unless-stopped

  openldap:
    image: osixia/openldap
    container_name: openldap
    environment:
      PUID: "1000"
      PGID: "1000"
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "${DUCKDNS_SUBDOMAIN}"
      LDAP_DOMAIN: "${DUCKDNS_SUBDOMAIN}.local"
      LDAP_BASE_DN: "dc=${DUCKDNS_SUBDOMAIN},dc=local"
      LDAP_ADMIN_PASSWORD: "${LDAP_ADMIN_PW}"
      LDAP_CONFIG_PASSWORD: "${LDAP_CONFIG_PW}"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "true"
      LDAP_TLS_VERIFY_CLIENT: "never"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "false"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    volumes:
      - ${DOCKER_CONFIGS}/openldap/config/ldap:/var/lib/ldap
      - ${DOCKER_CONFIGS}/openldap/config/slap.d:/etc/ldap/slapd.d
      - ${DOCKER_CONFIGS}/openldap/config/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
    ports:
      - 389:389
      - 636:636
    command: --copy-service
    restart: unless-stopped
```

### site-confs/default:
```
server {
        listen 80;
        listen [::]:80;
        server_name _;
        return 301 https://$host$request_uri;
}

# redirect non-www, or blank subdomain traffic to www subdomain
server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        server_name mysite.duckdns.org _;

        # all ssl related config moved to ssl.conf
        include /config/nginx/ssl.conf;

        return 301 https://www.mysite.duckdns.org$request_uri;
}

# main server block
server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;

        root /config/www;
        index index.html index.htm index.php;

        server_name www.mysite.duckdns.org;

        # enable subfolder method reverse proxy confs
        include /config/nginx/proxy-confs/*.subfolder.conf;

        # all ssl related config moved to ssl.conf
        include /config/nginx/ssl.conf;

        # enable for ldap auth
        include /config/nginx/ldap.conf;

        client_max_body_size 0;

        location / {
                try_files $uri $uri/ /index.html /index.php?$args =404;
        }

        location ~ \.php$ {
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass 127.0.0.1:9000;
                fastcgi_index index.php;
                include /etc/nginx/fastcgi_params;
        }

}

# enable subdomain method reverse proxy confs
include /config/nginx/proxy-confs/*.subdomain.conf;
# enable proxy cache for auth
proxy_cache_path cache/ keys_zone=auth_cache:10m;
```

### ldap.conf:
```
    location /login {
        resolver 127.0.0.11 valid=30s;
        set $upstream_ldap ldap-auth;
        proxy_pass http://$upstream_ldap:9000;
        proxy_set_header X-Target $request_uri;
    }

    location = /auth {
        resolver 127.0.0.11 valid=30s;
        set $upstream_ldap ldap-auth;
        proxy_pass http://$upstream_ldap:8888;

        proxy_pass_request_body off;
        proxy_set_header Content-Length "";

        proxy_cache auth_cache;
        proxy_cache_valid 200 10m;
        proxy_cache_key "$http_authorization$cookie_nginxauth";

        proxy_set_header X-Ldap-URL      "ldap://openldap";

        #proxy_set_header X-Ldap-Starttls "true";

        proxy_set_header X-Ldap-BaseDN   "ou=users,dc=mysite,dc=local";

        proxy_set_header X-Ldap-BindDN   "cn=admin,dc=mysite,dc=local";

        proxy_set_header X-Ldap-BindPass "#######";

        proxy_set_header X-CookieName "nginxauth";
        proxy_set_header Cookie nginxauth=$cookie_nginxauth;

        proxy_set_header X-Ldap-Template "(&(uid=%(username)s)(memberOf=cn=siteaccesspublic,ou=groups,dc=mysite,dc=local)

    }
```

### heimdall.subdomain.conf:
```
# make sure that your dns has a cname set for heimdall

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name heimdall.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    include /config/nginx/ldap.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        auth_request /auth;
        error_page 401 =200 /login;

        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_heimdall heimdall;
        proxy_pass https://$upstream_heimdall:443;
    }
}
```
