### ISSUE TITLE
custom ssl port causes problem with reverse proxy with medusa.subdomain.conf

### ISSUE THREAD

**Issue by waz1500** [linuxserver/docker-letsencrypt#298]
I have set a custom SSL port on my letsencrypt container. **443** is mapped to **1443**. 
I access my containers by changing the wildcard variable on my domain with the specified port added onto the end. All my subdomain.conf files are the default since I'm using linuxserver containers managed by docker-compose and it's .yaml file. 

I access my containers like this for example:
https://sonarr.domain.duckdns.org:1443 and https://radarr.domain.duckdns.org:1443. 
This works for most of my docker containers such as radarr and sonarr except the medusa container. 

On trying to access the medusa container via https://medusa.domain.duckdns.org:1443 leads to a white page
> Loading…
> If this is taking too long,
> click **here** to show the page

Its somewhat connecting (I can see the favicon and it has Medusa in the browser title) but it's not redirecting to the /home landing page.

When I change the port back to it's default 443 accessing https://medusa.domain.duckdns.org works and successfully redirects to https://medusa.domain.duckdns.org/home

I believe there is something in the medusa subdomain.conf file which isn't liking a custom port on the docker-letsencrypt and was wondering if someone could suggest a fix for me and those who want a custom ssl port.

This could be related to issue #76 but unsure since my other containers are working under a custom ssl set. 

**Steps to reproduce the problem:**
1. Change port on the letsencrypt container from 443 to something else such as 1443. 
2. Enable the medusa.subdomain.conf file in proxy-confs.
3. Try accessing the medusa container via your domain but append the custom port to it. 
4. Result stuck at landing page. 
5. Change back the custom port from 1443 back to 443. Recreate the container, and accessing the domain works.     

I've included my conf files. 
```
  medusa:
    image: linuxserver/medusa
    container_name: medusa
    volumes:
      - ~/.config/docker/medusa:/config
      - /home/monty/torrents/ANIME_MEDUSA:/downloads
      - /home/monty/Media/ANIME/:/anime
    ports:
      - 8081:8081
    restart: always
    environment:
      - PUID=1001
      - PGID=1001
      - TZ="Europe/London"
```
```
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1001
      - PGID=1001
      - TZ="Europe/London"
      - URL=domain.duckdns.org *redacted
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=*redacted
      - EMAIL=*redacted
      - DHLEVEL=2048
      - ONLY_SUBDOMAINS=false
    volumes:
      - ~/.config/docker/letsencrypt:/config
    ports:
      - 1443:443
      - 180:80
    restart: unless-stopped
```

```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name medusa.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /login;

        include /config/nginx/proxy.conf;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        resolver 127.0.0.11 valid=30s;
        set $upstream_medusa medusa;
        proxy_pass http://$upstream_medusa:8081;
    }
}

```
