### ISSUE TITLE
502 Bad Gateway with bridge network.

### ISSUE THREAD

**Issue by adamradocz** [linuxserver/docker-letsencrypt#324]
The following setting gives me 502 Bad Gateway:
```
version: "2"
services:

  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    depends_on:
      - duckdns
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      - EMAIL=X
      - URL=X
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns      
      - DUCKDNSTOKEN=X
      - ONLY_SUBDOMAINS=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/appdata/letsencrypt:/config
  
  boinc-manager-web:
    image: adamradocz/boinc-manager-web
    container_name: boinc-manager-web
    restart: always
    ports:
      - "8000:80"
      - "8001:443"
    volumes:
      - /opt/appdata/boinc-manager-web:/app/BoincManager
      - /opt/appdata/letsencrypt/keys/letsencrypt:/https
```

If I switch the network from bridge to host at the boinc-manager-web, it works. Is it related that the two images expose the 80 and 443? The port mapping shouldn't resolve that?
