### ISSUE TITLE
GEOIP2 not found

### ISSUE THREAD

**Issue by crobibero** [linuxserver/docker-letsencrypt#335]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	
```
nginx: [emerg] dlopen() "/var/lib/nginx/modules/ngx_stream_geoip2_module.so" failed (Error relocating /var/lib/nginx/modules/ngx_stream_geoip2_module.so: ngx_stream_add_variable: symbol not found) in /etc/nginx/modules/http_geoip2.conf:1
```

My log is spammed with this line.

Host: Debian

Docker-compose:
```
 letsencrypt:
        cap_add:
            - NET_ADMIN
        container_name: letsencrypt
        image: linuxserver/letsencrypt:latest
        ports:
            - "80:80"
            - "443:443"
        restart: always
        volumes:
            - /usr/appdata/letsencrypt/config:/config
        environment:
            - TZ=America/New_York
            - PGID=1001
            - PUID=1001
            - EMAIL=$email
            - URL=$domain
            - SUBDOMAINS=wildcard
            - VALIDATION=dns
            - DNSPLUGIN=cloudflare
        networks:
            - frontend
```
