### ISSUE TITLE
Persisting certificates

### ISSUE THREAD

**Issue by kirbyfu** [linuxserver/docker-letsencrypt#422]
Hi, a novice question but what should I do so that the certificates generated by the container are persisted to the host machine so that they aren't revoked and regenerated when I rebuild my `letsencrypt` image?

I was under the assumption that mounting `/config/keys` would prevent the revocation but I noticed that when I made changes to my frontend app (and thus the files that are placed in `config/www`), letsencrypt would log this despite none of the ENV variables in my docker-compose file changing

> Different validation parameters entered than what was used before. Revoking and deleting existing certificate, and an updated one will be created 

docker-compose.yml
```yml
version: '3.7'

services:
  letsencrypt:
    build:
      context: ./
      dockerfile: Dockerfile-prod
    container_name: letsencrypt
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      # persist keys so we don't create a new cert each time image is rebuilt
      - /letsencrypt/keys:/config/keys
      - ./nginx/prod.conf:/config/nginx/site-confs/default
    environment:
      - PUID=1050
      - PGID=1050
      - URL=${DOMAIN}
      # - SUBDOMAINS=www,
      - VALIDATION=http
      - EMAIL=${LETSENCRYPT_EMAIL}
      - TZ=Australia/Sydney
```

Dockerfile-prod
```Dockerfile
FROM node:10.16.0-alpine AS build

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# cache dependencies
COPY client/package.json /usr/src/app/package.json
RUN npm install

ADD client /usr/src/app
RUN npm run build

FROM linuxserver/letsencrypt
COPY --from=build /usr/src/app/build /config/www
```
