### ISSUE TITLE
Do not overwrite cli.ini

### ISSUE THREAD

**Issue by koseduhemak** [linuxserver/docker-letsencrypt#452]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
/config/etc/letsencrypt/cli.ini should not get deleted or modified if present on a mounted docker volume.

## Current Behavior
The file somehow got deleted. I think if docker-compose.yml is edited and new domains are inserted for ssl certification, the whole folder /config/etc/letsencrypt will be newly created / overwritten.
I am using cli.ini for cloudflare DNS validation, as the propagation seems to need more time than 10s (default).

## Steps to Reproduce

1. on a already configured instance, with cli.ini present, just add another (sub)domain you want to secure with letsencrypt to docker-compose.yml

## Command used to create docker container (run/create/compose/screenshot)

```
version: "3.1"
services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - URL=mydomain.com
      - SUBDOMAINS=test.example,test2.example,test3.example
      - ONLY_SUBDOMAINS=true
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - EMAIL=XXX
      - DHLEVEL=2048 #optional
      - STAGING=false #optional
    volumes:
      - /appdata/volumes/letsencrypt:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: always
```
