### ISSUE TITLE
[Future request] Seperate certificates for seperate domains

### ISSUE THREAD

**Issue by MayNiklas** [linuxserver/docker-letsencrypt#479]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

This is an feature request!

------------------------------

## Expected Behavior

I'm using an reverse proxy, to host different sites on the same server. Maybe I host sites for different clients or purporses on the same server. I would want to have a different certfificate for each domain. Is there a possible workarround? Changing the cert within every nginx config manually woulnd't be a problem.

## Current Behavior

The container generates a single certifacate for different alias domains. By inspecting the certificate within the browser, someone could look into all the sites hosted behind the reverse proxy.  

## Steps to Reproduce

1. Adding different domains under SUBDOMAINS and EXTRA_DOMAINS
2. Inspecting the certificate within firefox shows me all the different domains

## Future request:
In my opinion, there should be an option for seperating the certificates.
1. Certs saved as the name of the Domain
2. Somehow referencing those in the nginx config files

## Environment
**OS:** Debian 10
**CPU architecture:** x86_64 Intel(R) Xeon(R) Gold 6230
**How docker service was installed:** apt: deb [arch=amd64] https://download.docker.com/linux/debian buster stable

## Command used to create docker container (run/create/compose/screenshot)

I'm using docker-compose:
```
version: "3"
services:
  letsencrypt_nginx:
    image: linuxserver/letsencrypt
    # cap_add:
    #   - NET_ADMIN
    environment:
      - PUID=33
      - PGID=33
      - TZ=Europe/Berlin
      - URL=DOMAIN.de
      - ONLY_SUBDOMAINS=true
      - SUBDOMAINS=subdomain1, subdomain2, subdomain3, subdomain4, subdomain5, subdomain6
      - VALIDATION=http
      - EMAIL=webmaster@mymail.de
      - DHLEVEL=2048
      - EXTRA_DOMAINS=DOMAIN2.de, DOMAIN3.de
    volumes:
      - ./config:/config
    ports:
      - 80:80
      - 443:443
      - 8843:8843
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external:
      name: web
```
